name: GitHub Actions Demo - Class 05.01 - Compila y Genera PDF
run-name: ${{ github.actor }} Testing Actions in Marketplace - Compila .Net & Genera PDF - Class 05-01 🚀
on: 
  push:
jobs:
  job-01:
    name: Prepeare runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: '9.0.x'
            
      - name: Instalar Dependencias
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore
  
  job-02:
    needs:  job-01
    name: Markdown to PDF and HTML
    runs-on: ubuntu-latest
    
    steps:
      - name: Generacion de PDF
        uses: actions/checkout@v3
      - name: Use Markdown to PDF Action  
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
      
